### ISSUE TITLE
Doesn't restart countdown with redux

### ISSUE THREAD

**Issue by luluhoc** [ndresx/react-countdown#113]
Hey,

I'm using Redux for the state controller, When I get the new expiring date from API, the countdown timer doesn't restart the countdown. It just updates the countdown with a new date it says 10 minutes but doesn't start the countdown without refreshing the page.

**Comment by ndresx** [comment]
Hi, did you try providing the new date as `key` prop to fully remount the component?

**Comment by ArthurGerbelot** [comment]
Same issue here. I have an expiration date coming from Redux and Countdown isn't refreshing to the new date when it's updated. I tried to use `key` but did nothing

**Comment by ndresx** [comment]
If the date actually changes and you have really used the `key` prop, it should change, at least in some way because it's a new component instance that's getting generated at this point.

**Comment by ndresx** [comment]
I'm closing this. If you still have questions, please feel free to re-open.
