### ISSUE TITLE
Animate the counter effect

### ISSUE THREAD

**Issue by timrombergjakobsson** [ndresx/react-countdown#119]
Hi, is there any way of affect the way the timer ticks to achieve something like this https://codepen.io/jsrider/pen/ExPmgJM? I can't find any examples of it being done, and does not seem to have any support of it in the lib?

**Comment by ndresx** [comment]
Hi, no sorry, you would have to implement this on your own. It might work with a custom renderer, but again, there is nothing there yet that supports this kind of animation.

**Comment by timrombergjakobsson** [comment]
@ndresx ok thanks for your answer!
