### ISSUE TITLE
Show Counter Only In Minutes & Seconds

### ISSUE THREAD

**Issue by MahmudulHassan5809** [ndresx/react-countdown#120]
how can i counter  time only in minutes & seconds ?

**Comment by pjdiiori** [comment]
also wondering this.

You could use a renderer function and manually format the display but that kind of seems to defeat the purpose of using this component!

**Comment by ndresx** [comment]
Hi, there's currently no built-in way that would allow you to do this. The easiest thing is probably to set `daysInHours` to `true`, and then, as @pjdiiori already said, defining a custom renderer where you would break down the hours into minutes.

**Comment by MahmudulHassan5809** [comment]
Thanks i have solved this problem using custom  renderer.
