### ISSUE TITLE
Using the rendered time in other components

### ISSUE THREAD

**Issue by julizamt** [ndresx/react-countdown#122]
I´m making a web-game with a countdown, and under certain circumstances, the clock should stop. 
Then I need to grab the amount of time left, and perform some calculations. 
Is that possible with react-countdown? to grab the time value at any point?
I´ve tried to figure it out but couldn´t get it from the docs.
Thanx!

**Comment by ndresx** [comment]
Hi, the only way I could think of would be through the `onTick` callback. There is currently no other way to access this data.

**Comment by julizamt** [comment]
Ok, thanks!
