### ISSUE TITLE
How to stop the countdown programmatically?

### ISSUE THREAD

**Issue by karland** [ndresx/react-countdown#125]
Hi, @ndresx thanks for this excellent library. Is there a chance to stop the countdown programmatically from the outside, that means without a button. I am not sure how else coud I trigger the `api.stop()`?

I was looking for something like this maybe:

```
<Countdown
  date={expiryTimestamp}
  stop={condition}
/>
```

I could not find anything in the docs. Is there any possibility? Thanks.

**Comment by ndresx** [comment]
Hi, there's currently no other way to do this besides using the API.

**Comment by karland** [comment]
Thanks for the quick answer. Unfortunately, I don't get. How do you access it then trough the api?
The docs read. 

"The countdown component exposes a simple API through the getApi() function that can be accessed via component ref. It is also part (api) of the render props passed into renderer if needed."

Is there an example? Many thanks.

**Comment by ndresx** [comment]
Here are some examples of how it could be used.

- https://codesandbox.io/s/examples-e8ld2
- https://github.com/ndresx/react-countdown/tree/master/e2e
- https://github.com/ndresx/react-countdown/blob/master/examples/src/CountdownApi.tsx

**Comment by karland** [comment]
OK, I have found this solution and it works. 

```JSX
import React, { useRef, useEffect } from "react"

// ...

const countdownRef = useRef()

useEffect(() => {
  if (isSuccess) {
    countdownRef.current.api.stop()
  }
 }, [isSuccess])

// ...

<Countdown
  ref={countdownRef}
  date={expiryTimestamp}
/>
```

Thanks for your help.
