### ISSUE TITLE
countdown restarts when a state changed

### ISSUE THREAD

**Issue by kylemod** [ndresx/react-countdown#126]
I have a state from parent component `App.js` and pass my function `change state` as a props to child component and i am pretty sure that the state is not connected to countdown component.

**Comment by ndresx** [comment]
Hi @kylemod, are you using Hooks? Just to understand it, you are updating the `children` of the countdown component and this one causes the countdown to update? Is there anything else you are changing, or do you maybe have an example to reproduce the issue?

**Comment by kylemod** [comment]
I make a `darkMode` state from my `App.js` then pass the states as a props on `Navbar` component

Example :

`App.js`
```jsx
const [isDark, setIsDark] = useState(false)

return (
...
  <Navbar isDark={isDark} setIsDark={setIsDark} />
...
  // My home component with countdown
)
```

`Navbar.js`

```jsx
const Navbar = ({ isDark, setIsDark}) => {
const toggleDark = () => {
    setIsDark(isDark => !isDark)
  }
}
```

My navbar and countdown component are in different component

I tried useEffect hook for my countdown component but still it restarts.

**Comment by ndresx** [comment]
What are the props you are passing down to the countdown? I know that there is currently a bug with the `renderer` and `children` props (I still need to fix this). In your case, I guess it could have something to do with the way you are passing down the `date` unless you are using one of the props mentioned before.

**Comment by kylemod** [comment]
No, i didn't pass any props in countdown component,  i just followed your guide from [#custom-renderer-with-completed-condition](https://github.com/ndresx/react-countdown#custom-renderer-with-completed-condition)

**Comment by ndresx** [comment]
Ok, this sounds like the bug I was mentioning before. The only workaround you could try is to use `useCallback` or a class component so that the `renderer` function doesn't get newly created on every rerender. Otherwise, I fear there is currently no way for you to do this with this component. 😞

**Comment by ndresx** [comment]
This should be hopefully fixed now!

**Comment by johanguse** [comment]
I have the same problem... my clicks on button are resetting the counter... in this two function handleClickOffer handleCountdownEnd

https://github.com/johanguse/ic-frontend-recruitment-test/blob/main/src/components/Card/index.tsx

**Comment by ndresx** [comment]
@johanguse Try to use `useRef` to store the countdown's `date` prop. Then it shouldn't reset any longer.

**Comment by lexuantunght** [comment]
I used it in a react hooks and also got count down restart!

**Comment by teddybee** [comment]
@ndresx Same issue here, the 10 second timer always restarts around 8-9

**Comment by snoopydev20** [comment]
> @johanguse Try to use `useRef` to store the countdown's `date` prop. Then it shouldn't reset any longer.

Could you please explain in detail?

**Comment by mledwards** [comment]
useMemo with an empty dependency array fixed this for me, as it never tried to reset the countdown

```
const time = React.useMemo(() => {
    return Date.now() + 120 * 1000;
  }, []);
```

**Comment by JusticeFrancis** [comment]
i solved this issue by removing the date from my functional component 
e.g creating a constant const date = Date.now() above my export default function or const functional component

above not inside the component containing the countdown timer component

i believe on state change the date .now also updates as well and the countdown timer has to restart when both the date.now and countdown timer are within thesame functional or class component


hope this helps

**Comment by Bertie-indemnity78** [comment]
> useMemo with an empty dependency array fixed this for me, as it only set the time on initial render
> 
> ```
> const time = React.useMemo(() => {
>     return Date.now() + 120 * 1000;
>   }, []);
> ```





https://accessibility705.github.io/t7_pdsBmR_bcAR_pR_xMMT_ehPPGs2jfmyIrVb1WbRrT1dss74a_MCjhgcZHSWxkAeJJvnKv/
