### ISSUE TITLE
coutdown freezes sometimes and works sometimes

### ISSUE THREAD

**Issue by RushiChandalia** [ndresx/react-countdown#141]
hello there, 
I am using this lib for the date countdown but its weirdly freezes sometimes and works sometimes.

you can check the countdown here [https://app.sollotto.io/purchase](url)

please help out as i am not getting any solution to this,

thanks for the package :)

**Comment by ndresx** [comment]
Hi, I've checked it out and it doesn't freeze for me (waited 1-2 minutes). Does it literally get stuck for you for a couple of seconds? Are you updating the state/date prop in some way while it is running?

**Comment by saeedhemmati** [comment]
Same issue. countdown sometimes not working as expected. sometimes countdown from 02:00 minutes takes a longer time from 2 minutes and sometimes it takes precisely 2 minutes which is expected.
