### ISSUE TITLE
Get how much time passed or left

### ISSUE THREAD

**Issue by developerdesigner18** [ndresx/react-countdown#142]
I have a requirement to switch the user every 3 minutes. I have implemented this countdown library but I want to implement that after 3 minutes user can enable the switch button. 

So is it possible to get how much time passed or simply how to get 3 minutes passed or not!?

**Comment by ndresx** [comment]
Hi, there would be the two callbacks `onComplete` and `onTick` who could help you with that. If the countdown is set to 3 minutes, then the `onComplete` callback should suffice, but either way, you should be able to get the time from one of the passed callback arguments.

**Comment by developerdesigner18** [comment]
Okay, will do it. Thank you
