### ISSUE TITLE
Cant seem to make the "overtime" prop do anything...am I using it correctly? 

### ISSUE THREAD

**Issue by elietech** [ndresx/react-countdown#146]
Is my usage of the overtime prop correct?  I would expect this to countdown from 5, into negative numbers to infinity, but it doesn't seem to do anything: 

` <Countdown date={Date.now() + 5000} overtime={true} />,`

**Comment by ndresx** [comment]
Hi, this seems to be working here https://codesandbox.io/s/awesome-colden-ff6ln?file=/index.js.

**Comment by elietech** [comment]
Ya, that is definitely odd.  Curious why it won't work in my app...

**Comment by ndresx** [comment]
Do you maybe rerender your component in some way? How do you pass the `date` prop?

**Comment by elietech** [comment]
I don't know what i was doing wrong before, but it works fine now.  Must have just had a long day.  Sorry for the trouble.
