### ISSUE TITLE
use multiple countdown

### ISSUE THREAD

**Issue by amirsam00** [ndresx/react-countdown#168]
hi, i want to use multiple countdown instance in tr of a table and I want to delete the row whenever it's countdown finished,
How can I do this? 

`renderer({hours, minutes, seconds, completed, ...rest}){
        if (completed) { // i need here tr related to this coundown
            return <span>expire</span>;
        } else {
            // Render a countdown
            if (seconds == 0)
                return '';
            return <div className="timerContainer"><span className="sp_timer">{seconds}</span></div>;
        }
    }
render() {
        const currentRow = this.props.row;
        return (
            <table>
                <tr>
                    <td>{currentRow.qty}</td>
                    <td>{currentRow.registerTime}</td>
                    <td>
                        <Countdown
                            date={Date.now() + currentRow.remainedSeconds * 1000}
                            key={currentRow.id}
                            renderer={this.renderer}
                        />
                    </td>
			<tr>
			</table>
			)
}`

**Comment by ndresx** [comment]
Hi, check the https://github.com/ndresx/react-countdown#oncomplete callback function. With that, you should be able to accomplish what you are trying to do!

**Comment by amirsam00** [comment]
thanks,
how can i access parent td of each countdown that completed in oncomplete function and then remove it?

**Comment by ndresx** [comment]
Hmm, there are multiple ways. For example, using different `onComplete` callbacks as mentioned before, or using lodash to put an index of your row into the arguments list when called.
