### ISSUE TITLE
Make date props not optional

### ISSUE THREAD

**Issue by Moritz-Steinle** [ndresx/react-countdown#175]
Since the `date` prop is declared required in the docs, it should be in the code.
 Currently however it's the following:
 `export interface CountdownProps extends React.Props<Countdown>, CountdownTimeDeltaFormatOptions, Omit<LegacyCountdownProps, 'onComplete'> {
    readonly date?: Date | number | string;`
    [...]

**Comment by ndresx** [comment]
True, I must have changed that for legacy reasons, will check if this can be corrected! Thank you!
