### ISSUE TITLE
why taking system time component should take proper time 

### ISSUE THREAD

**Issue by omkar199** [ndresx/react-countdown#183]
its taking system suppose you change your system time then its taking system time

**Comment by ndresx** [comment]
Hi, could you please elaborate on this issue?

**Comment by omkar199** [comment]
how can i set the start time
right now its taking system time as start time
i wont to set like 12 am my timer should start what can i do

**Comment by omkar199** [comment]
@ndresx please help me

**Comment by ndresx** [comment]
You can set the date via `date` prop https://github.com/ndresx/react-countdown#date. Here are also some examples https://github.com/ndresx/react-countdown#examples.

**Comment by ndresx** [comment]
Closing, please feel free to reopen if this doesn't solve your problem!
