### ISSUE TITLE
autostart after new value

### ISSUE THREAD

**Issue by cellulosa** [ndresx/react-countdown#189]
Hi and thanks for the great plugin.

I am building a [pomodoro-like](https://pomofocus.io/) timer and have a button to trigger a 5 mins break after the timer run for 25 mins. The button calls `handleTakeBreak`, which set the time to 5 minutes and then run the `handleStartClick` (which is used by the start/pause button).

    const handleTakeBreak = () => {
      setCountdownTime(Date.now() + countdownBreak);
      handleStartClick();
    };

    const handleStartClick = () => {
        if (countdownApi?.isPaused() || countdownApi?.isStopped()) {
            countdownApi?.start();
            return;
        }
        countdownApi?.pause();
      };

The time gets the new "break" time but it does not starts unless I press the start/pause button (I can see it only launches `onMount`).

What am I missing?

Ps. I resolved it by using `autoStart={autostart}` and setting the variable as needed with `const [autostart, setAutostart] = useState(false);` but it would be good to understand if that's the intended behaviour?

**Comment by ndresx** [comment]
Hi, `autoStart` is only considered when the countdown first mounts, after that, you'd have to control it via API calls (if I understand your problem).

**Comment by ndresx** [comment]
Closing, please feel free to reopen if this doesn't solve your problem!
