### ISSUE TITLE
React Countdown makes Snapshot Tests Unreliable

### ISSUE THREAD

**Issue by AshtonKem** [ndresx/react-countdown#19]
Integrating react-countdown with react-native snapshot tests makes them finicky. Depending on test order and machine load, the snapshot happens before or after the first countdown second happens, resulting in the test being flakey.

I believe the solution would be to manage the clock for the tests, do you know an easy way to do that?

**Comment by ndresx** [comment]
Although it's probably too late for an answer (sorry) - you are right with your assumption of solving this by managing the clock. In case you are using Jest, you could do something like this:
```js
const now = jest.fn(() => 1482363367071);
Date.now = now;
```
