### ISSUE TITLE
On Safari on iOS (15.4) countdown is broken, displays NaN instead of numbers

### ISSUE THREAD

**Issue by indicava** [ndresx/react-countdown#191]
On Safari on iOS (15.4) countdown is broken, displays NaN instead of numbers

See example screenshot from Chrome on Windows and Safari on iOS - https://imgur.com/a/VxYjMEP

**Comment by ndresx** [comment]
Hi, could you provide the code and `date` you are passing into the component?

**Comment by ndresx** [comment]
Closing, please feel free to reopen if this doesn't solve your problem!
