### ISSUE TITLE
hide hours

### ISSUE THREAD

**Issue by alimusavi67** [ndresx/react-countdown#193]
how I can hide hours?
I need 00:00 format

**Comment by SammyAbukmeil** [comment]
Were you able to resolve this @alimusavi67 ?

**Comment by isherwood** [comment]
See https://github.com/ndresx/react-countdown/issues/120.

**Comment by alimusavi67** [comment]
> Were you able to resolve this @alimusavi67 ?

See https://github.com/ndresx/react-countdown/issues/120.
