### ISSUE TITLE
zeroPadLength does not work with renderer function.

### ISSUE THREAD

**Issue by oyepez003** [ndresx/react-countdown#2]
Hi thanks for this component, it is great!!...

I have the next problem with the zeroPadLength:

Without renderer:
> <Countdown date={this.state.promotion.startDateTime} />

Result: **1:00:03:36** 

With renderer (same of docs):

```
renderClock = ({ days, hours, minutes, seconds, completed }) => {
        if (completed) {
        // Render a completed state 
            this.forceUpdate()
        } else {
            // Render a countdown 
            return <span>{days}:{hours}:{minutes}:{seconds}</span>;
        }
}
```

Result: **1:0:0:36**

**Comment by ndresx** [comment]
Hi, when using a custom renderer you need to call `zeroPad` yourself by importing it and wrapping the numbers like in this example (https://codesandbox.io/s/y31jlr7owz). Hope that helps!

**Comment by oyepez003** [comment]
Excellent @ndresx. Thanks for the tip, that was better than my own solution.

Best regards.

**Comment by artyhedgehog** [comment]
Would be really helpful if added to a basic example with renderer.
