### ISSUE TITLE
[Typescript] How to type ref ?

### ISSUE THREAD

**Issue by GautierT** [ndresx/react-countdown#202]
Hi. 

I'm using typescript and i need to type the countdownRef 
```
const countdownRef = useRef();

<Countdown
        ref={countdownRef}
        date={1000}
/>
```

What should I do ?
Thanks.

![image](https://user-images.githubusercontent.com/6089653/176677757-57595f7c-7012-43b7-b5a0-8f559597fef0.png)

**Comment by GautierT** [comment]
Thanks but the problem seems to be on the difference between RefObject and LegacyRef

![image](https://user-images.githubusercontent.com/6089653/177361238-3755af7b-802d-4778-955f-c10789cbb6b0.png)

**Comment by carlosriveroib** [comment]
If you create a ref with undefined
`const ref = useRef<HTMLDivElement> = useRef()`
the returned type is MutableRefObject<HTMLDivElement | undefined>

If you create a ref with null
`const ref = useRef<HTMLDivElement> = useRef(null)`
the returned type is RefObject<HTMLDivElement>

that was the problem

**Comment by ndresx** [comment]
Thank you!
