### ISSUE TITLE
Cannot Reset Time with key

### ISSUE THREAD

**Issue by HendryVarianto14** [ndresx/react-countdown#208]
Hello,

I tried to reset the time with changing the key whenever the timer completed.
But, the timer did not reset at all.

it works when i used the timer in the modal, but failed when i do it in a single page.
`
<Countdown
              date={startDate.current + 5000}
              key={reset}
              onComplete={() => setReset(prev => prev + 1)}
              renderer={({ formatted, completed }) => {
                if (completed) {
                  return (
                    <span
                      className={classes.hyperlink}
                      onClick={e => {
                        e.preventDefault();
                        setReset(reset + 1);
                      }}>
                      ReSend
                    </span>
                  );
                } else {
                  return (
                    <span>
                      <b>
                        {formatted.minutes}:{formatted.seconds}
                      </b>
                    </span>
                  );
                }
              }}
            />`

Im using Nextjs for development
any help? thanks

**Comment by HendryVarianto14** [comment]
Nvm. i messed up

**Comment by salman-ar-sar** [comment]
Can you share your complete code in a sandbox or something? I am having issues now.

**Comment by SalahAdDin** [comment]
> Can you share your complete code in a sandbox or something? I am having issues now.

In my case, it does not reset when closing a modal.

**Comment by HendryVarianto14** [comment]
> Can you share your complete code in a sandbox or something? I am having issues now.

For me, i used useMemo (dont know if its a good practice to use useMemo like this) to store the time, it goes something like this:
`const time = useMemo(() => {
    if (!reset) {
      return Date.now() + 60000;
    } else {
      return Date.now() + 60000;
    }
  }, [reset]);`
  
  So, every time i clicked the reset button, it changes the reset state, thus, the useMemo runs again and reapplied the time.
  It works, but you need to include autoStart to the props for the time to runs

**Comment by HendryVarianto14** [comment]
> > Can you share your complete code in a sandbox or something? I am having issues now.
> 
> In my case, it does not reset when closing a modal.

I never tried it, but try to use the flag of the modal as the key of the Countdown 
LMK if this works

**Comment by SalahAdDin** [comment]
> > > Can you share your complete code in a sandbox or something? I am having issues now.
> > 
> > 
> > In my case, it does not reset when closing a modal.
> 
> I never tried it, but try to use the flag of the modal as the key of the Countdown LMK if this works

which flag?

**Comment by HendryVarianto14** [comment]
> > > > Can you share your complete code in a sandbox or something? I am having issues now.
> > > 
> > > 
> > > In my case, it does not reset when closing a modal.
> > 
> > 
> > I never tried it, but try to use the flag of the modal as the key of the Countdown LMK if this works
> 
> which flag?

The Modal's flag. y'know, the `open={flag}`

**Comment by SalahAdDin** [comment]
> > > > > Can you share your complete code in a sandbox or something? I am having issues now.
> > > > 
> > > > 
> > > > In my case, it does not reset when closing a modal.
> > > 
> > > 
> > > I never tried it, but try to use the flag of the modal as the key of the Countdown LMK if this works
> > 
> > 
> > which flag?
> 
> The Modal's flag. y'know, the `open={flag}`

I have to check it again.
