### ISSUE TITLE
UTC

### ISSUE THREAD

**Issue by Cookiesale** [ndresx/react-countdown#217]
Having a problem ensuring the timer is consistent across all timezones.
How can I solve this countdown for UTC?
Current time string

 date='2022-10-18T16:00:00'

**Comment by ndresx** [comment]
Hi, the countdown's time left is the same across all time zones.

However, you could pass a custom https://github.com/ndresx/react-countdown#now function into the `Countdown` in case the `date` you are providing (like in the example) contains a time zone offset.

**Comment by ndresx** [comment]
I'm closing this for now. Please feel free to re-open if you have any further questions!
