### ISSUE TITLE
Maximum depth reached error

### ISSUE THREAD

**Issue by blockchain5992** [ndresx/react-countdown#218]
I am getting maximum depth reached error while adding as a timer in my application

**Comment by ndresx** [comment]
Hi, could you please provide an example of how you are using it?

**Comment by blockchain5992** [comment]
I am fetching date param from backend and want to show countdown timer for my contest. So I am adding Countdown component in return like this:
<Countdown
                    date={ abc?.xyz }
                    renderer={renderer}
 />
const renderer = ({ days, hours, minutes }) => {
    // Render a countdown
    return (
      <div>
        {" "}
        {days}
        <span>d</span>
        <span className="dot">:</span> {hours}
        <span>h</span> <span className="dot">:</span> {minutes}
        <span>m</span>
      </div>
    );
  };

So when I am opening my page it will not loaded and I got maximum depth limit reached error.

**Comment by ndresx** [comment]
Hi, is this still happening for you?

**Comment by MuhammadHadiofficial** [comment]
i'm also facing this issue when trying to update state in renderer function!

**Comment by ndresx** [comment]
Hi, you should avoid updating the state in any render function in React since state updates result in a rerender (and then the cycle starts again, and again => infinite loop) unless you manually prevent it in one of the other lifecycle methods.

**Comment by MuhammadHadiofficial** [comment]
I think oncomplete callback will handle the state updates right?

**Comment by ndresx** [comment]
It depends on what you would like to achieve, but yes, you could update the state in one of the callbacks, e.g., `onComplete`.

**Comment by MuhammadHadiofficial** [comment]
Thank you! I fixed my issue.

**Comment by ndresx** [comment]
I'm closing this. Please feel free to re-open or create a new issue if you still encounter this problem!
