### ISSUE TITLE
v2.3.3 not fully reflected?

### ISSUE THREAD

**Issue by sourabhxyz** [ndresx/react-countdown#219]
Hi, my `package.json` file tells that I am on version `2.3.3` (`"react-countdown": "^2.3.3",`) but [latest](https://github.com/ndresx/react-countdown/releases/tag/v2.3.3) update to `onComplete` is not reflected (as it is not firing up when given `date` was already passed) and when I navigate to its type, I see `readonly onComplete?: CountdownTimeDeltaFn | LegacyCountdownProps['onComplete'];` 
![image](https://user-images.githubusercontent.com/29835247/201517799-9115743b-af8a-4c87-b2d2-91c2ec31d054.png)
And not
```typescript
readonly onComplete?: (
    timeDelta: CountdownTimeDelta,
    completedOnStart: boolean
  ) => void | LegacyCountdownProps['onComplete'];
```
I installed the package via yarn.

**Comment by sourabhxyz** [comment]
Can see in [this](https://codesandbox.io/s/thirsty-shtern-owt989?file=/pages/index.tsx) sandbox link.

**Comment by ndresx** [comment]
Hi @sourabhxyz, yes, you are correct. Many thanks for noticing and reporting this issue!

This should be fixed with the latest release https://www.npmjs.com/package/react-countdown/v/2.3.4.
