### ISSUE TITLE
Module not found: Can't resolve 'lodash.isequal' in './node_modules/react-countdown-now/dist/Countdown.js'

### ISSUE THREAD

**Issue by evgimov** [ndresx/react-countdown#22]
After installing the module with "yarn add react-countdown-now" command, importing the Countdown component and trying "Custom & Conditional Rendering->Using a React Child for the Completed State" example I faced the following error:
./node_modules/react-countdown-now/dist/Countdown.js
Module not found: Can't resolve 'lodash.isequal' in '../node_modules/react-countdown-now/dist'

**Note:** installing the "lodash.isequal" package solved the issue.

Please, add to the README.md that "lodash.isequal" package needs to be installed and imported into the project.

**Comment by jadbox** [comment]
Same issue here

**Comment by ndresx** [comment]
Ouch, the problem should be fixed now with `v2.1.0`, is it? I think I have messed up its dependencies.

**Comment by evgimov** [comment]
The issue was fixed, thank you!

**Comment by bgwengineering** [comment]
having same issue after install load.isequal

**Comment by ndresx** [comment]
Hi @bgwengineering, the `react-countdown-now` package was deprecated quite a while ago. The new one https://npmjs.com/package/react-countdown (`react-countdown`) doesn't have a dependency on `load.isequal` anymore, so please try it with this new package!
