### ISSUE TITLE
Failed to minify the code from this file: react-countdown-now/dist/index.es.js:4 

### ISSUE THREAD

**Issue by mushinz** [ndresx/react-countdown#23]
When doing npm run build I have this error.
npm start works just fine.

Failed to minify the code from this file: 

 	./node_modules/react-countdown-now/dist/index.es.js:4

**Comment by ndresx** [comment]
Hi @mushinz, what plugins are you using for building and minifying your code? Also, could you please provide a more detailed error message if available?

**Comment by mushinz** [comment]
when using "webpack": "3.8.1", and "babel-core": "^6.26.3.

However I did update the the last version of react and everything works fine, however, with that old package.json, project doesn't work

**Comment by dintrans** [comment]
I'm using babel 6.26.0, webpack 3.12.0 and uglify-js@3 3.4.9. Uglify requires all the code to be in ES5 but in this case is receives a function with a default argument so it fails because there's a «=» instead of a «,». I didn't try to update react, i'm using 16.6.1, so i just downgraded to 1.3.0 and it's working fine.

**Comment by ndresx** [comment]
Have released a new version `v2.0.3` which should be working correctly now. Let me know if there's still something wrong with it, please!

**Comment by dintrans** [comment]
Thanks! 👍 I'll check it out.

**Comment by frangeris** [comment]
This is still failing but in other line

```
ERROR in client-9fa9d968474c5c594f54.js from UglifyJs
Unexpected character '`' [./node_modules/react-countdown-now/dist/index.es.js:13,0][client-9fa9d968474c5c594f54.js:189126,9]
```

**Comment by frangeris** [comment]
> I'm using babel 6.26.0, webpack 3.12.0 and uglify-js@3 3.4.9. Uglify requires all the code to be in ES5 but in this case is receives a function with a default argument so it fails because there's a «=» instead of a «,». I didn't try to update react, i'm using 16.6.1, so i just downgraded to 1.3.0 and it's working fine.

What package did you downgrade?

**Comment by ndresx** [comment]
@frangeris Do you maybe have a repo I could check out to repro this? Otherwise, I will give it another try.
I guess he was talking about v1.3.0 of this countdown plugin, that's the version before the build step was refactored.

**Comment by frangeris** [comment]
@ndresx Sorry, working on private repos and its hard to replicate cuz is on build process the issue

**Comment by ndresx** [comment]
@frangeris Sure, no problem. Well then, I will test a bit more, but your error message helps. The backtick shouldn't be there anymore.

**Comment by frangeris** [comment]
I tried to update the file and resolve all those conflicts directly, but as I resolve they appear, so I think the issue is not the code, your code its fine, the problem could be related to the way you are transpiling the final build.
