### ISSUE TITLE
 It does not restart on its own, as if after completing it, if we want to start it again, then it has to rerender the entire page from scratch.

### ISSUE THREAD

**Issue by ManojJyani0** [ndresx/react-countdown#245]
it is stuck when it is completed and to start it again rereander full page with navigate to another page or somthing

**Comment by reptincel-cpu** [comment]
same here

**Comment by sergiors** [comment]
same here

**Comment by ravirasadiya** [comment]
is there any update on it?

**Comment by ndresx** [comment]
Hi, a bit late to this, but the easiest way to restart the countdown is by providing a `key` "prop" to the Countdown. On completion, you can reset this key to a new value, and the countdown will remount itself.

Alternatively, you can use the countdown's API. Here is an example you could try and check out https://github.com/ndresx/react-countdown/blob/master/examples/src/CountdownApi.tsx.
