### ISSUE TITLE
zeroPadTime doesn't look like working

### ISSUE THREAD

**Issue by rooooonald** [ndresx/react-countdown#248]
Even I set zeroPadTime={2}, still no zero is padded. ;(

`<Countdown
                  date={event.datetime}
                  renderer={renderer}
                  zeroPadTime={2}
                  onComplete={timesUpHandler}
                />`

**Comment by pedram-taheri** [comment]
{hours ? hours : "00"}:{minutes ? minutes : "00"}:{seconds ? seconds : "00"}
use this code in render function to show 00 

const renderer = ({ hours, minutes, seconds, completed }) => {
  if (completed) {
    // Render a completed state
    return <Completionist />;
  } else {
    // Render a countdown
    return <span>{hours ? hours : "00"}:{minutes ? minutes : "00"}:{seconds ? seconds : "00"}</span>;
  }
};

**Comment by pedram-taheri** [comment]
{hours ? hours : "00"}:{minutes ? minutes : "00"}:{seconds ? seconds : "00"}
use this code in render function to show 00
```
const renderer = ({ hours, minutes, seconds, completed }) => {
if (completed) {
// Render a completed state
return ;
} else {
// Render a countdown
return {hours ? hours : "00"}:{minutes ? minutes : "00"}:{seconds ? seconds : "00"};
}
};
```

**Comment by ndresx** [comment]
Hi, a bit late to this, but in case anyone is running into the same issue.

When using a custom `renderer`, the formatted output can be found in the `formatted` object provided to the `renderer` function. 

```ts
<Countdown date={Date.now() + 10000} zeroPadTime={2} renderer={({ formatted: { hours, minutes, seconds } }) => {
    return (
      <>
        {hours}:{minutes}:{seconds}
      </>
    );
  }}
/>;
```
