### ISSUE TITLE
Warning: Failed prop type: Invalid prop `date` supplied to `Countdown`.

### ISSUE THREAD

**Issue by zkeyword** [ndresx/react-countdown#25]
"react": "^16.2.0",
"react-countdown-now": "^2.1.0",
"typescript": "^3.2.2",

JSX 元素类不支持特性，因为它不具有“props”属性。

不能将类型“{ daysInHours: true; date: any; }”分配给类型“{}”。
类型“{}”上不存在属性“daysInHours”。

**Comment by zkeyword** [comment]
<div className='time'>
                                        <Countdown
                                            daysInHours
                                            date={dayjs(item.createdAt).add(
                                                1,
                                                'day'
                                            )}
                                        />
                                    </div>

**Comment by zkeyword** [comment]
It is recommended to add formatting function

**Comment by ndresx** [comment]
Hi @zkeyword, you have to convert your `dayjs` object back into either a JavaScript date, string or number. This should work without getting the error:

````
<Countdown daysInHours date={dayjs(item.createdAt).add( 1, 'day' ).toObject()} />
```

**Comment by zkeyword** [comment]
thanks
