### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by zaadevofc** [ndresx/react-countdown#256]
![image](https://github.com/ndresx/react-countdown/assets/93970726/e96138cd-e4ac-43aa-afc6-abe1b4f4cfc4)

![image](https://github.com/ndresx/react-countdown/assets/93970726/8606329e-eb98-4e89-8022-877e113e7685)

I don't know why, even though I just installed it and followed the documentation correctly. 

This error occurred when I entered countdown into the component. 

but when I delete the countdown component the error will disappear.

**Comment by ndresx** [comment]
Hi, it looks like the import of the countdown component is wrong. If this is still relevant, please provide more details.

**Comment by ndresx** [comment]
I'll close this issue. If you have any additional or other questions, please feel free to re-open or create a new one!
