### ISSUE TITLE
Combining custom rendered and onComplete callback breaks the countdown

### ISSUE THREAD

**Issue by lmartins** [ndresx/react-countdown#26]
Hi,

I'm using a where I have both a custom renderer and a `onComplete` callback as seen bellow:

```jsx
<Countdown
              date={Date.now() + 5000}
              renderer={this.renderCountdown}
              onComplete={() => {
                this.setState({ isAvailable: true });
              }}
```

```jsx
renderCountdown({ hours, minutes, seconds, completed }) {
    if (completed) {
      // Render a complete state
      return (
        <div className="countdown">
          Available <span>now!</span>
        </div>
      );
    } else {
      // Render a countdown
      return (
        <div className="countdown">
          Available in
          <span className="clock">
            {hours} hours {minutes} minutes {seconds} seconds
          </span>
        </div>
      );
    }
  }
```

The reason I have it like this is because I have other child components that need from that `isAvailable` state property, but with this combination at the end of the countdown the custom renderer will not enter the `completed` verification, instead will always show the clock stopped at the initial start time.

Thanks so much for any help and the super useful component!

**Comment by ndresx** [comment]
Hi! I have copied your code into this sandbox https://codesandbox.io/s/l214pkovpz. It seems to work properly, could you tell me please what exactly doesn't work?

**Comment by ndresx** [comment]
Closing this, please re-open if the problem still exists.

**Comment by lmartins** [comment]
@ndresx Hey Martin, sorry I've missed your initial comment.
On my project I can replicate it consistently, so my guess is something else is interfering. For now I've approached differently. Thanks so much for looking into this.

**Comment by ZuechB** [comment]
I am also having this issue, I downloaded the npm "react-countdown-now": "^2.1.0" and using the latest ver. of next.js this.setState({ blah: true }) does not work within the complete method call for me.

**Comment by Raphaww** [comment]
the problem still exist in 2.3.2 and react 16.8

https://codesandbox.io/s/musing-raman-51hms

**Comment by dagouzhi** [comment]
```
<Countdown
  key={Date.now() + 5000}
  date={Date.now() + 5000}
  renderer={this.renderCountdown}
  onComplete={() => {
    this.setState({ isAvailable: true });
  }}
/>
```

**add key** 
it works for me

**Comment by nxic** [comment]
For who's still facing this problem. I've just used the isAvailable state in my renderer function. It works like a charm for me

```typescript
import * as React from 'react';
import Countdown from 'react-countdown';

export const CountdownComponentDemo = () => {
  const [isComplete, setIsComplete] = React.useState<boolean>(false);

  const renderer = ({ days, hours, minutes, seconds }) => {
    if (isComplete) {
      return <div>Ended</div>;
    }

    return <>
      <div><span>{ days }</span> <span>days</span></div>
      <div><span>{ hours }</span> <span>hours</span></div>
      <div><span>{ minutes }</span> <span>minutes</span></div>
      <div><span>{ seconds }</span> <span>seconds</span></div>
    </>;
  };
  
  return <>
    <Countdown
      date={Date.now() + 10000}
      renderer={renderer}
      onComplete={({ completed }) => { setIsComplete(completed); }}
    />
  </>;
}
```
