### ISSUE TITLE
Unexpected behavior when starting countdown

### ISSUE THREAD

**Issue by mantas102** [ndresx/react-countdown#27]
Hi, I am trying to use Countdown component with autoStart set to false. I added button with onClick handler to trigger start function via refs. If event handler only contains call to start timer function, everything seem to work just fine, however if I add more logic to event handler and lets say I use `this.setState({})` to modify some of my states, it starts to behave unexpectedly (countdown starts at greater time when initially set to, also it resets every time I invoke start function).
Sample code: https://codesandbox.io/s/m3nwrlw539

**Comment by ndresx** [comment]
Hi, `setState` causes a re-render of your component and the `date` passed into the countdown is `now` + 1 minute, so whenever it re-renders, it re-starts the countdown with this given date. You could try to do something like this https://codesandbox.io/s/5494159o1x.

**Comment by mantas102** [comment]
Oh, right! I have not tried that for some reason.. Thank you for great answer and sorry for a bit silly question.
