### ISSUE TITLE
onComplete doesn't fire when tab is not focused on mobile

### ISSUE THREAD

**Issue by omerdn1** [ndresx/react-countdown#28]
How can I enforce an onComplete in a scenario where a user is switching tabs/apps on mobile and then goes back after the timer has supposedly run out?
Right now the user goes back and sees 00:00 but the onComplete function wasn't executed.

![big-not_fixed](https://user-images.githubusercontent.com/10265367/52685958-43b79400-2f7e-11e9-9e4c-f136210b560a.jpg)

**Comment by ndresx** [comment]
Hi, it may depend on what you are trying to do. I have created an example here https://codesandbox.io/s/43667k7q2w, tested it on my Android phone and it seems to be working, even if the tab is not active. Does this example work on your test device?

**Comment by ndresx** [comment]
Closing this one, feel free to re-open please if needed.
