### ISSUE TITLE
Get current time

### ISSUE THREAD

**Issue by cesoftinfo** [ndresx/react-countdown#30]
How to get current time from Counter in any moment?

**Comment by ndresx** [comment]
Hello, you could get the current time via the `onTick` callback https://github.com/ndresx/react-countdown#ontick. Would that work?

**Comment by andyngo** [comment]
Hi, sorry to bump an old thread but is there an example of this? I'd like to get the remaining time but it's not clear to me how `onTick` could provide the remaining time.

**Comment by ndresx** [comment]
Hi @andyngo, where exactly do you need this time? The `onTick` callback receives an argument with the following values. Is this what you are looking for?

```
{ total, days, hours, minutes, seconds, milliseconds, completed }
```

Reference: https://github.com/ndresx/react-countdown#calctimedelta

**Comment by andyngo** [comment]
Actually, yes. That does work. Your explanation finally made it click for me. Thank you!
