### ISSUE TITLE
Examples fail to compile

### ISSUE THREAD

**Issue by miketheman** [ndresx/react-countdown#31]
Hello! I've been trying to use this library to build a countdown timer, as it has good documentation, and looks cool.

I've been struggling to understand how to structure a React component that wraps the `Countdown` component, so as to provide a method for controlling the timer, so I looked to the `examples/` directory - and [this file](https://github.com/ndresx/react-countdown/blob/d6831e8acb9a76cf84544a4a9fc722724a04d377/examples/src/CountdownApi.tsx) looked like the right thing.

I'm pretty new to React, and don't yet know the idioms and patterns, and this is also in Typescript - which I'm not familiar with, so eventually I checked out the repo and tried to run the examples to see if I could figure it out.

However, I get this error message after `yarn install && yarn start`:

```
Failed to compile.

/Users/miketheman/workspace/other/react-countdown/examples/node_modules/@types/react-dom/node_modules/@types/react/index.d.ts
Type error: Duplicate identifier 'LibraryManagedAttributes'.  TS2300

    2665 |         // We can't recurse forever because `type` can't be self-referential;
    2666 |         // let's assume it's reasonable to do a single React.lazy() around a single React.memo() / vice-versa
  > 2667 |         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
         |              ^
    2668 |             ? T extends React.MemoExoticComponent<infer U> | React.LazyExoticComponent<infer U>
    2669 |                 ? ReactManagedAttributes<U, P>
    2670 |                 : ReactManagedAttributes<T, P>
```

I was wondering if you had seen this before, or had any idea how this might be happening?

```shellsession
$ which node
/usr/local/bin/node
$ node --version
v11.14.0
$ which yarn
/usr/local/bin/yarn
$ yarn --version
1.15.2
```

**Comment by ndresx** [comment]
Hi and thanks for the issue report!

I'm not quite sure what this error means, but I have updated all the npm packages used by the examples and it should be working again. If it still doesn't work, please try to delete the parent's `node_modules` folder. These somehow seem to be interfering with the ones in the `examples` folder!

**Comment by miketheman** [comment]
Thanks, that appears to have solved the issue! I also removed all other node_modules folders - even the one in my home folder's root, and now it works. Thanks!
