### ISSUE TITLE
Setting the controlled=true stops the countdown.

### ISSUE THREAD

**Issue by bojanm95** [ndresx/react-countdown#33]
Hello, awesome job with building this nice component, I have an issue however. When I set controlled prop to true it stops the timer. Probably it's supposed to work like that, but in that case would you be able to give me an example of how the function that sets the date prop should look like? Thanks in advance.

**Comment by ndresx** [comment]
Hi and thank you. Does this example work for you https://codesandbox.io/s/0gxsb?

**Comment by bojanm95** [comment]
It works great, thanks!
