### ISSUE TITLE
zeroPadTime is not working when using custom render

### ISSUE THREAD

**Issue by Jravvit** [ndresx/react-countdown#35]
I use custom render Like this
`    <Countdown
                date={Date.now() + 10000}
                zeroPadTime={2}
                renderer={renderer}
              />
`
But i take 0:0:0 format 

How can i use it?

**Comment by Jravvit** [comment]
I can solve this problem.

When i make custom component.
I receive props not {days, hours, minutes, seconds}

Below code

```
<Countdown date={Date.now() + 10000} renderer={renderer} />


const renderer = props => {
  return (
    <span>
      {props.formatted.days}:{props.formatted.hours}:{props.formatted.minutes}:{props.formatted.seconds}
  );
};
```

**Comment by OFFLlNE** [comment]
My `props` do not have the `formatted` field :(
