### ISSUE TITLE
use inside formik is not working as expected.

### ISSUE THREAD

**Issue by danywheeler** [ndresx/react-countdown#36]
![image](https://user-images.githubusercontent.com/8910772/58923710-5cd59200-8773-11e9-86f3-1c6d61738064.png)

I'm using formik to implement form like the above, the 获取验证码 is the Countdown component, using this setup the countdown will render when ever input change blur is happened states update this is how form generally works, the problems is that  the Countdown will render too much unnecessary times, and with this code below
```javascript
componentDidUpdate(prevProps: CountdownProps): void {
    if (!isEqual(this.props, prevProps)) {
      this.setTimeDeltaState(this.calcTimeDelta());
    }
  }
```
generated error countdown time delta.

**Comment by ndresx** [comment]
How does the countdown's configuration look like? What exactly is the error and would it be possible to get a test build on https://codesandbox.io or similar?

**Comment by danywheeler** [comment]
sure, here the sandbox I just created: https://codesandbox.io/s/youthful-bash-2o47f
click '获取验证码' first validate the mobile field then if it's correct fires an sendOTP then start counting, if you then change the form any way triggers formik setState causes the update, the countdown is not working as expected.

**Comment by danywheeler** [comment]
@ndresx any how, the Countdown do need to implement some sort of shouldComponentUpdate, and in componentDidUpdate there are need more logic for the correct behavior.

**Comment by ndresx** [comment]
@danywheeler Thanks for the demo, somehow it breaks on clicking submit (`_this.props.onSubmit is not a function`) though for some reason.

Did you try to store the countdown's date in the component's internal state? I guess the problem for you is that it always resets itself at the moment?

**Comment by danywheeler** [comment]
you are correct, I was just not looking the obvious, still we can do some performance optimization, like call  setTimeDeltaState based on specific condition?

**Comment by ndresx** [comment]
The countdown should only update itself on time changes/the given interval (this can be defined via prop https://github.com/ndresx/react-countdown#intervaldelay), or when the given props are changing. What kind of condition are you thinking about that could improve it even more?

**Comment by ndresx** [comment]
I'll keep an eye on this, but will be closing this for now. Please feel free to re-open if needed!
