### ISSUE TITLE
Count up / reverse count?

### ISSUE THREAD

**Issue by nathanwaters** [ndresx/react-countdown#40]
Any hacks or methods to achieve this?

**Comment by ndresx** [comment]
Hi, you could try to do something like this: https://codesandbox.io/s/morning-dream-vbin8.

**Comment by nathanwaters** [comment]
Awesome thankyou! Much better approach than what I was trying with onTick

**Comment by gdrbyKo1** [comment]
I came here looking for an answer to this question just to find out that the the link shared by @ndresx no longer works.
So here's what I came up with, in case it helps someone else in the future:
```js
const someDate = new Date('2020-12-18T00:00:00Z');
<Countdown
    date={new Date(0)}
    now={() => - new Date().valueOf() + someDate.valueOf()}
    overtime
/>
```
This will count up from `someDate`.
