### ISSUE TITLE
Countdown numbers stay static when using the now prop

### ISSUE THREAD

**Issue by alderwebdev** [ndresx/react-countdown#42]
We are using the now prop to change the default Date.now() so that it will always be Mountain Standard Time no matter where people are using the website. But whenever we use it, the numbers do not continue to countdown, they just stay static on the initial load up numbers. But whenever we take off the now prop, it works just fine and the numbers will continue to count down. Please help and advise if possible.

**Comment by ndresx** [comment]
The `now` prop is a replacement for `Date.now`, so it should also return a dynamic number to calculate the difference with. Do you maybe have an example of your setup?

**Comment by khutty** [comment]
I've been experiencing a similar issue with the numbers not counting down. Although if I reload the page that appears to get them ticking again. Not sure if its just coincidence but I'm also using now prop to change default Date.now(). I tried removing it like OP suggested but that didn't appear to fix my issue.

**Comment by ndresx** [comment]
Hi! I have prepared a small example which is using the `now` prop: https://codesandbox.io/s/fragrant-platform-8s1i7

Would be nice if you could share what you are trying to achieve (or even some code) to check it out, but it's really just replacing ´Date.now` and does nothing more to it. Maybe the docs are also not clear about it? Would appreciate any further details!

**Comment by noor-codes** [comment]
@ndresx I want to pass down the current time from the server instead of Date.now() that can be anything based on the user settings. When I add the same timestamp to the now prop, the countdown stops.

any idea?

links above are broken.

```jsx
// Todo: Calculate current time based on the server. Client side can't be valid all the times.

<Countdown
  key="countdown"
  date={resetTokenLife}
  now={() => now} // SSR current date
  renderer={renderer}
/>
```

**Comment by noor-codes** [comment]
Maybe there is a better way to do it :)
