### ISSUE TITLE
How program event in specific second before countdown complete?

### ISSUE THREAD

**Issue by carlosmajimo** [ndresx/react-countdown#47]
Hi ndresx, i was wondering how to code an event in a second specific before the countdown is completed

**Comment by ndresx** [comment]
Hi @carlosmajimo, you could try to use the [`onTick`](https://github.com/ndresx/react-countdown#ontick) callback for this purpose. It also receives the current time delta where you could check for that "one second" before it ends, if that's what you meant?

**Comment by carlosmajimo** [comment]
Thank you man, sorry for the inconvenience

**Comment by ndresx** [comment]
You're more than welcome!
