### ISSUE TITLE
Something wrong with Safari

### ISSUE THREAD

**Issue by Starpuccino** [ndresx/react-countdown#49]
Hello there,
I have some problems on macOS Safari 12.1.2 @version2.1.1
```jsx
renderer = ({ days, hours, minutes, seconds, completed }) => {
    console.log(days, hours, minutes, seconds, completed);
}

let startDate = new Date('2019-12-12 00:00:00');

<Countdown date={startDate} renderer={this.renderer} />
```
it works good on Chrome
but `NaN – NaN – NaN – NaN – false` on Safari

**Comment by anthonyvialleton** [comment]
Same here. 
I'm using : '2019-08-14 15:19:00' as date prop.
To fix it I have to pass a different type of content for the `date` prop such as a `moment` date type instead.

**Comment by ndresx** [comment]
Hi, you would have to use an **[ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)** compatible date format as Safari cannot parse these "other" date formats anymore, Chrome still does. The countdown itself doesn't do any date formatting on its own and purely relies on the browser implementation.

In this case, the format would be something like _(notice the `T` in-between)_

```js
new Date('2019-12-12T00:00:00');
```

This should hopefully fix this issue?

**Comment by Starpuccino** [comment]
```javascript
console.log('Solved, thank you very much :)');
```

**Comment by ndresx** [comment]
Have updated the docs to make the `date` prop usage and its supported formats a bit more clear https://github.com/ndresx/react-countdown#date. Thanks for the initial report!
