### ISSUE TITLE
The padding zero function seem tobe not working ?

### ISSUE THREAD

**Issue by longluffy** [ndresx/react-countdown#55]
The padding zero function seem tobe not working ?
can anyone please check that ?

**Comment by ndresx** [comment]
Hi @longluffy, could you please provide some more information about how you use the component (props)?

**Comment by longluffy** [comment]
Sorry it's my fault, when using custom renderer, the attribute zeroPadTime wont pass to the custom renderer. We have to use it like ``` {zeroPad(minutes)}:{zeroPad(seconds)} ``` in the renderer ! 
I got it, it's working perfectly :D 
Thank you and im closing  the question
