### ISSUE TITLE
Countdown resets before the end

### ISSUE THREAD

**Issue by SoTDarksoul** [ndresx/react-countdown#56]
I have a countdown that refresh a page when it's completed.
Some time before that, I show a modal.
When the modal is shown, the countdown starts again, making the refresh never happening.

Here's some parts of the code : 

```
render() {
const renderer = ({ hours, minutes, seconds, completed }) => {
      console.log('test : ' + seconds);
      return true;
    };
return (
     <Countdown
          date={Date.now() + 15000}
          renderer={renderer}
          onTick={({ hours, minutes, seconds, completed }) => {
            if (seconds === 10) {
              this.showModal();
            }
          }}
          onComplete={() => window.location.reload()}
        />
);
  }
```

Any idea?

**Comment by ndresx** [comment]
Hi, could it be that your component is re-rendering because of the modal action and therefore causing the countdown to restart? You could try to move the `date` value into your component's local `state` so that it only generates the start date once => Countdown shouldn't restart anymore.

**Comment by SoTDarksoul** [comment]
It might, I will try this today and update my answer.

**Comment by ndresx** [comment]
@SoTDarksoul Did you find out anything yet by any chance?

**Comment by ndresx** [comment]
Closing this for now, please feel free to reopen if needed!

**Comment by pavinduLakshan** [comment]
@ndresx can confirm your solution works
