### ISSUE TITLE
Years missing

### ISSUE THREAD

**Issue by marcmetz** [ndresx/react-countdown#57]
Years would have been great. That's the only reason I can't use that one.

**Comment by ndresx** [comment]
Hi @marcmetz, thanks for your comment. I will consider adding it to one of the next updates if more people are interested in this!

In the meantime, you could try using the custom `renderer` (https://github.com/ndresx/react-countdown#renderer) as it receives the total time + days and then just look for a days-to-years converter to display it based on your needs.

Please let me know if you have any more questions or need help!

**Comment by marcmetz** [comment]
Thank you @ndresx . I appreciate the consideration. I will look into your suggestion, thank you!
