### ISSUE TITLE
zeroPadTime in custom renderer

### ISSUE THREAD

**Issue by meeshh** [ndresx/react-countdown#60]
i have the example of the custom renderer but the zeroPadTime is showing this format 0:0:0 while i needed to be like the following 00:00:00

```
const renderer = ({ hours, minutes, seconds, completed }) => {
		if (completed) { 
			// Render a complete state
			return <Completionist />;
		} else {
			// Render a countdown
			return (
				<span>
					{hours}:{minutes}:{seconds}
				</span>
			);
		}
	};
```

**Comment by ndresx** [comment]
Hi @meeshh!

The callback function receives a `formatted` property that contains all of these values - formatted accordingly to the component's input props.

```js
const renderer = ({ formatted: { hours, minutes, seconds }, completed }) => {...}
```

You could also import [zeroPad](https://github.com/ndresx/react-countdown#zeropadvalue-length--2) manually und use it like this:
```js
{zeroPad(hours)}:{zeroPad(minutes)}:{zeroPad(seconds)}
```

**Comment by meeshh** [comment]
thanks @ndresx it works like a charm

**Comment by findawei** [comment]
This would probably be useful if it was in the docs to begin with. Thanks for a great tool!
