### ISSUE TITLE
How to pause the timer?

### ISSUE THREAD

**Issue by skswain96** [ndresx/react-countdown#61]
@ndresx Can you please show an example of how to pause the timer and get paused time.

**Comment by ndresx** [comment]
Hi @skswain96, here's a basic example of what you could do https://codesandbox.io/s/examples-2pjm5.

**Comment by skswain96** [comment]
> Hi @skswain96, here's a basic example of what you could do https://codesandbox.io/s/examples-2pjm5.

Hi @ndresx, thanks a lot, but I am new to react, and I have never worked with typescript, can we achieve this without using typescript?

**Comment by ndresx** [comment]
Yes! https://codesandbox.io/s/examples-e8ld2.

**Comment by ndresx** [comment]
Closing this, please feel free to re-open or create a new issue if you have more questions. Thank you!

**Comment by skswain96** [comment]
> Closing this, please feel free to re-open or create a new issue if you have more questions. Thank you!

This is resolved, Thank You

**Comment by gino8080** [comment]
Please can you make an example with pause and custom render ?

thank you for this great lib!
