### ISSUE TITLE
autoStart false, countdown shortly shows seconds passed before rerendering and starting properly

### ISSUE THREAD

**Issue by christianstrang** [ndresx/react-countdown#63]
This issue is probably related to hooks but here goes:
My countdown is set to autostart false and to run for 60 seconds, when I start the timer, I first reset the date and key prop, otherwise the countdown would start running with the already passed seconds (e.g. if I wait 3 seconds before starting the countdown, the countdown would start at 0:57 instead of 1:00).

The parent component sets the "startTimer" prop to true, which in return sets autoStart to true as well:

```javascript
useEffect(() => {
  let newCountdown = Date.now() + durationInSeconds * 1000;
  setCountdownKey(newCountdown);
  setCountdownDate(newCountdown);
}, [startTimer]);

.
.
.

<Countdown
  key={countdownKey}
  date={countdownDate}
  autoStart={startTimer}
  renderer={({ minutes, seconds }) => (
    <span>
      {minutes}:{zeroPad(seconds)}
    </span>
  )}
/>
```

The only issue I have right now is, once I start the countdown, it first jumps to the time passed (the same as described above with e.g. waiting 3 seconds, jumping to 0:57) and then resets correctly to 1:00 and goes down from there.

Is there a reason for the time jump with autostart false or am I not properly resetting the date and key before starting?

**Comment by christianstrang** [comment]
Well damn, two seconds after posting, I fixed my specific issue by not relying on a state for the key and date and instead just using it directly:

```javascript
<Countdown
  key={Date.now() + durationInSeconds * 1000}
  date={Date.now() + durationInSeconds * 1000}
  autoStart={startTimer}
  renderer={({ minutes, seconds }) => (
    <span>
      {minutes}:{zeroPad(seconds)}
    </span>
  )}
/>
```

**Comment by ndresx** [comment]
Hey, I have tried to reproduce your described behavior here https://codesandbox.io/s/busy-glitter-eqp69 and it seems to be working the way you would have initially implemented it, without the time jumping. _Maybe I got something wrong there._

I have one question though! Would you have expected the countdown to start on an `autoStart` prop change? Currently, this isn't the case, which why you are probably using the key, but just curious what you think about how it should be.

**Comment by christianstrang** [comment]
Hi :)

> Would you have expected the countdown to start on an autoStart prop change?

No, I didn't expect it to, it was a better fitting workaround for me: the countdown is in a child component (and called/started from a parent) and I previously used a ref with forwardRef, though this was a bit too messy for my taste which is why I switched to the autostart+key approach.

The only difference from your example is that I use Material-UI, but I doubt that is whats causing the jump.

**Comment by ndresx** [comment]
Hmm, do you mean the `renderer` prop or the renderer through NextJS?

There shouldn't be a difference when using one or not (the example still works with a `renderer` function like yours). I'm not so familiar with SSR, but maybe the date gets pre-generated server-side and then again dynamically created by JS which in the end causes this jump?

**Comment by christianstrang** [comment]
I mean the renderer function from the countdown. I don't think its related to SSR, but it still might be related to NextJs, not sure. For now I "fixed" the issue by having two renderers, a default one, that always renders "1:00" and the "real" renderer that only gets picked when the timer has started.

**Comment by ndresx** [comment]
It's a bit hard to reproduce this now, but if you got anything to share in that direction to look into a bit more it would be great. I'm not quite sure how the date could get stale within the countdown and then update with this jump. Thank you already though for the feedback!

**Comment by christianstrang** [comment]
Thank you for your help! I don't know what happened but I removed the fakeRenderer approach and it just works (the same code didn't work before without a timejump). Not sure if there was some kind of caching involved or I didn't handle sideeffects properly, but my current code now works as intended :)
