### ISSUE TITLE
Countdown resets on any state update

### ISSUE THREAD

**Issue by auto200** [ndresx/react-countdown#64]
I know that component rerenders naturally on state change but it's really frustrating for Countdown.
Look at the demo i made: https://codesandbox.io/s/lingering-night-sn8jd
Easy way to fix it is to memo the Countdown component itself but combined with forwardRef it totally crashes for me.
Any workarounds?

**Comment by ndresx** [comment]
Hi, you could store the `date` itself in the state like here https://codesandbox.io/s/nervous-hodgkin-rh6v4.

**Comment by auto200** [comment]
ok that pretty much covers my question. Thanks
