### ISSUE TITLE
Countdown sometimes doesn't start

### ISSUE THREAD

**Issue by jimmycarlinco** [ndresx/react-countdown#66]
Hello,

please help me debug this issue: the countdown sometimes doesn't start (like 1 in 5 times) and stays static. Any idea what might be causing this?

Using custom renderer rest is default.
```
const Completionist = () =>
  (<span className="ui-highlight" style={{ backgroundColor: blueGrey[900] }}>
    Ended
  </span>);

// Renderer callback with condition
const renderer = ({ formatted: { hours, minutes, seconds }, completed }) => {
  if (completed) {
    // Render a completed state
    return <Completionist />;
  }
  // Render a countdown
  return (
    <span
      className={classnames('ui-highlight')}
      style={{ color: '#FFF', backgroundColor: lightGreen[800] }}
    >
      {minutes}:{seconds}
    </span>
  );
};
```

in component:

...
`                        <Countdown date={expiry_date} renderer={renderer} />
`
...

**Comment by ndresx** [comment]
Hi, could you please try to also set the `key` attribute with the expiry date as value? My suspicion is that once it completes, updating it via props alone is not enouzzz5ghbN to restart it anymore.

**Comment by ndresx** [comment]
I'll leave this open for some more days. However, it would be great if you _(or maybe someone else?_) got any more information on this issue. I have tried to reproduce it without success.

**Comment by ST2-EV** [comment]
They key thing fixed it for me
