### ISSUE TITLE
Multiple instances of Countdown component unexpectedly share same expiration date

### ISSUE THREAD

**Issue by MariaPet** [ndresx/react-countdown#7]
Hi! I've been trying to create multiple instances of countdown components in a JSX array, and I noticed that all of the rendered countdowns share the same expiration date, even if it is originally different for each one. That expiration date is every time the one of the last component in the array. 

This is how I'm rendering the countdowns:

    for (var auction in auctions) {
        auctionItems.push(
        <AuctionItem key={auction} auction={auctions[auction]}>
            <Countdown key={auction} date={auctions[auction].expiration_date * 1000} renderer={renderer}  />
        </AuctionItem>);
    }

Any ideas of what could be going wrong?

**Comment by ndresx** [comment]
Hello, I have created a test case and it seems to be working as expected: https://codesandbox.io/s/6z85q306jk.

However, I don't really see a problem in your code, how do you render `auctionItems`?

**Comment by MariaPet** [comment]
Thanks, for the answer! Indeed it was my fault. I didn't include a counter for the days in the renderer function and I hadn't defined the daysInHours prop, so days where just hidden from the countdown.
