### ISSUE TITLE
Cleanup resources on componentWillUnmount?

### ISSUE THREAD

**Issue by dhowe** [ndresx/react-countdown#71]
Currently I am simply pausing the timer (assuming it has not finished), however I wonder if this cleans up all resources sufficiently?

**Comment by ndresx** [comment]
Hi, it will clean up/clear the timer's interval and therefore stop any background calculations while it's paused. Does this answer your question or are you referring to something else?

**Comment by dhowe** [comment]
Thanks. Specifically clearing the id returned from setTimeout or setInterval I guess. I was looking for a stop or destroy function, if I know that I won't be using that countdown anymore on unmount. But if pause does the job, then that's great. Though actually it looks like the id is cleared internally on componentWillUnmount.. so is pause() not needed there?

**Comment by ndresx** [comment]
It depends on what you want to do. If you would still like to show the countdown, then pausing it makes sense and only the interval will get cleared. If you don't need it anymore at all, `componentWillUnmount` will be called by React internally which clears up the interval and the component's instance.

`componentWillUnmount` and `pause` are clearing the interval internally as you can see here. https://github.com/ndresx/react-countdown/blob/master/src/Countdown.tsx#L186
