### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by jodiedoubleday** [ndresx/react-countdown#74]
I need my countdown to countdown in a different timezone.
I.e I'm based in the UK but I'm building for a client in the US.
However the countdown always seem to be UK time.
Where does React Countdown pull the current time from?
is this based on the servers location? the locale on the html file?

**Comment by ndresx** [comment]
Hi, the countdown uses JS' `Date.now()` as base for time calculations. You could either pass in a custom function here (`now`) which considers the timezone by using Moment.js, for example, or change the `date` accordingly.

The countdown itself is not aware of this information.

**Comment by jodiedoubleday** [comment]
thank you, great answer!±
