### ISSUE TITLE
[question] Is there a way to pass custom messages/props to the renderer

### ISSUE THREAD

**Issue by jodiedoubleday** [ndresx/react-countdown#75]
I'm using a content management system, and want to pass in a message when the countdown completes. Is there a way to pass custom props through to the renderer i.e `message={content}`?

**Comment by ndresx** [comment]
Hi, there is no way to pass down props, however, check out the examples here for showing a customized completed state https://github.com/ndresx/react-countdown/blob/master/README.md#custom--conditional-rendering

Does that help?

**Comment by ndresx** [comment]
I'm closing this, however, please feel free to re-open at any time if you have further questions!
