### ISSUE TITLE
Don't understand how to use the API to run start()

### ISSUE THREAD

**Issue by danbt** [ndresx/react-countdown#78]
Hey there guys,

Can't quite understand how to use the API to run "start()" based off a button click event.

Any advice would be appreciated.

Thanks

**Comment by ndresx** [comment]
Hi, there is an example you could try and check out https://github.com/ndresx/react-countdown/blob/master/examples/src/CountdownApi.tsx (unfortunately not in a sandbox yet).

You need to create/get a `ref`erence of the `Countdown` component, which then exposes its API through `getApi` that allows you to call methods like `start` and `pause` (see https://github.com/ndresx/react-countdown#api-reference).

Let me know if you need more help with it!

**Comment by ndresx** [comment]
I'm closing this for now. Please feel free to re-open at any time if you have further questions!

**Comment by SalahAdDin** [comment]
I don't get it: how can i use it with hook?

I have this in my render:
```
const Timer = ({ hours, minutes, seconds, completed, api, props }) => {
  const { className } = props;
  let time = completed ? `Is completed!` : `${hours}:${minutes}:${seconds}`;
  api.start();
  return (
    <StepLabel
      alternativeLabel
      StepIconComponent={StepIcon}
      StepIconProps={{
        classes: {
          root: className
        },  
        icon: time
      }}
    />
  );
};
```

But i'm getting this:

> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Why?

**Comment by ndresx** [comment]
@SalahAdDin The function gets called on every render update. You can try to change it like this:

```ts
useEffect(() => {
  api.start();
}, [api]);
```

That should only execute it on the first function call or whenever `api` changes.

**Comment by SalahAdDin** [comment]
@ndresx I have to use this inside of the same component, right?

**Comment by ndresx** [comment]
@SalahAdDin Yes, try to replace it with the line `api.start();`

**Comment by SalahAdDin** [comment]
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Even when i do this:
```
function Timer ({ hours, minutes, seconds, completed, api, props }) {
  const { className } = props;
  let time = completed ? `Is completed!` : `${hours}:${minutes}:${seconds}`;

  React.useEffect(() => {
    api.start();
  }, [api]);

  return (
    <StepLabel
      alternativeLabel
      StepIconComponent={StepIcon}
      StepIconProps={{
        classes: {
          root: className
        },  
        icon: time
      }}
    />
  );
};
```

**Comment by ndresx** [comment]
Where do you declare this? Could you show me the code with the `Countdown` being used please?

**Comment by SalahAdDin** [comment]
```

        <Step className={classes.skillTestStepper} key="timer">
          <Countdown
            date={Date.now() + defaultTime}
            autoStart={false}
            renderer={Timer}
            className={classes.timer}
          />
        </Step>
      </Stepper>
```

Here.

**Comment by ndresx** [comment]
@SalahAdDin ok, sorry, I think I get it now. You cannot use a Hook for the `renderer` prop but could use another function in-between as a work-around.

For example, `TimerCountdown` is used as a `renderer` prop here, and `Timer` is then created within this functional component. https://codesandbox.io/s/vigilant-darkness-58kpv

**Comment by SalahAdDin** [comment]
@ndresx You did it, but i think it is a littler tricky right now, i hope we will get the hook soon.

But, I'm having a problem with it: my idea to use this is start the counter when i do click in a button, i declared the started time in the time where the use come to the site:
```
        <Step className={classes.skillTestStepper} key="timer">
          <Countdown
            date={Date.now() + defaultTime}
            autoStart={false} //TODO: I don't get how use it to start when the test begins, https://github.com/ndresx/react-countdown#api-reference
            renderer={TimerCountdown}
            className={classes.timer}
            isBegun={isBegun}
          />
        </Step>
```

`isBegun` defines if the test was begun or not, and I changes when the use does click on the button, but is the use take his time to read or bla bla bla, when he makes click i get this:
![deepin-screen-recorder_Select area_20200317013712](https://user-images.githubusercontent.com/5034215/76805486-eda3c880-67ef-11ea-88cb-06d34a590462.gif)
It is a delay in the counter, a deviation, it does not start to one hour, it starts with the time the user used to think or whatever.

How can i control it?

**Comment by ndresx** [comment]
@SalahAdDin Could you try moving the `date` value into your app/local `state` too, and then just update it whenever you click the "Start" button?

`autoStart` doesn't change anymore after first mount in the current countdown version, which could be considered a bug. However, you could set the `key` prop on the `Countdown` with the updated `date` as a value, and at the same time also set `autoStart` to `true`. This should fix all of your problems.

**Comment by SalahAdDin** [comment]
@ndresx 
```
 const [timerTime, setTimerTime] = React.useState(Date.now() + defaultTime);

  React.useEffect(() => {
    if (isBegun) setTimerTime(Date.now() + defaultTime);
  }, [isBegun]);


          <Countdown
            autoStart={false}
            date={timerTime}
            renderer={Timer}
            className={classes.timer}
            isBegun={isBegun}
          />
        </Step>
```
If i let `autoStart` as true it will begin at time, if i leave `timerTime` as none, the timer won't be showed, and right now it is showed to be an hour but it stills begin with delay.

![deepin-screen-recorder_Select area_20200317015857](https://user-images.githubusercontent.com/5034215/76807544-c4863680-67f5-11ea-9780-2fc076d453da.gif)

**Comment by ndresx** [comment]
@SalahAdDin Try to set the `key` prop as well.

```ts
          <Countdown
            key={timerTime}
            autoStart={false}
            date={timerTime}
            renderer={Timer}
            className={classes.timer}
            isBegun={isBegun}
          />
```

**Comment by SalahAdDin** [comment]
And yeap, it worked very well. some times it renders `0:59:59` as my initial `TimerTime` is `
  const [timerTime, setTimerTime] = React.useState(Date.now() + defaultTime);`, but it is well.
Why `key` is obligatory?

I hope it would be easier with hooks.

**Comment by ndresx** [comment]
Glad it worked, at least in some way. I'm definitely working on improving this in the future!

The `key` prop (https://reactjs.org/docs/lists-and-keys.html#keys) comes from React and basically re-mounts/initializes the component and in this case, it means that date + other props are getting picked up correctly.

**Comment by SalahAdDin** [comment]
@ndresx I don't know if this is a big problem or not, but i want to report this warning:
```
./src/components/Elements/SkillTest/modules/components/Timer.js
  Line 15:6:  React Hook React.useEffect has a missing dependency: 'api'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

**Comment by ndresx** [comment]
@SalahAdDin Could it be that you forgot to add `[api]` as a second argument in the `useEffect` call?

**Comment by SalahAdDin** [comment]
yeah, it is,  but i'm not sure if it could be a problem to put both then as arguments in `useEffect`.

**Comment by ndresx** [comment]
Everything that is used in `useEffect` should be set as a dependency, if possible. Otherwise, you will have to change your linting rules.

**Comment by SalahAdDin** [comment]
@ndresx Did you finish the hook? Thanks.
