### ISSUE TITLE
when restarting the timer, the countdown doesn't visibly count down 

### ISSUE THREAD

**Issue by sriksm19** [ndresx/react-countdown#8]
i have a component which shows an expiring token and once expired, a button is clicked to reset the expiry which resets with a new token and a new expiry time. the newer time gets passed and updates but the count down renders only the first time. i have to keep re-rendering the element to see the change in the timer's state else the countdown is stuck. if i refresh the page it works fine. do i need to restart a flag to restart its internal setTimeout or so?

thanks

**Comment by ndresx** [comment]
Hi @sriksm19, so I first thought that this could be a bug (still not sure), but take a look at this please: https://codesandbox.io/s/l79o7z4177

Is this the way you try to use it?

**Comment by sriksm19** [comment]
no. I use a render prop. within the render prop's component i try to update <Countdown /> date prop upon expiry. although it updates, the timer doesn't seem to be stuck at the new starting point, even though the countdown happens in the background

**Comment by ndresx** [comment]
Oh, yeah, that's not possible atm. Do you think it would be ok to check whether a new date was passed in after it is completed and then restart the countdown, or do you have a better idea?

**Comment by sriksm19** [comment]
*Do you think it would be ok to check whether a new date was passed in
after it is completed and then restart the countdown*
yes. how do i restart the rendering?

Srikanth Sethumadhavan

**Comment by ndresx** [comment]
For now, the only way to achieve this is by providing a `key` like in this example https://codesandbox.io/s/ykk86m6o29. I will add this functionality in one of the upcoming updates.

**Comment by sriksm19** [comment]
ok.. leme try this.. anyways, eagerly waiting for the update.. thanks :)

Srikanth Sethumadhavan

**Comment by darol100** [comment]
@ndresx Any update on this issue? I have been trying to re-render the countdown again once it stops but I got the same issue, where it gets stuck.

**Comment by darol100** [comment]
In my case, I have a countdown base on cron jobs and I needed to show a countdown base on the next cron job. 

So I ended up doing something similar to what @ndresx suggest, which is changing the date before the countdown gets stuck. 

I am still using the callback renderer function and changing the date on the last second.

This is an example code:

```javascript
// Renderer callback with condition 
const renderer = ({ hours, minutes, seconds, completed }) => {
  if (completed) {
     if (hours === 0 && minutes === 0 && seconds === 1) {
      
      axios
        .get(getNextEvent)
        .then((response) => {
         this.state.date = response.data.next_event;
        })
        .catch((error) => {
          console.log(error);
        });
    }
  } else {
    // Render a countdown 
    return <span>{hours}:{minutes}:{seconds}</span>;
  }
};
 
ReactDOM.render(
  <Countdown
    date={this.state.}
    renderer={renderer}
  />,
  document.getElementById('root')
);
```

***Note:*** This is kinda like a pseudocode of what I ended up doing not a copying pasting code.

**Comment by ndresx** [comment]
@darol100 Unfortunately no update yet, but will take a look at it asap. The solution with using the `key` attribute in the meantime should be ok though. Let me know if you need any further help!

**Comment by ivinamra** [comment]
Is there any way to use this as countup timer when provided with date less than current date or by using unix timestamp?

**Comment by darol100** [comment]
@ivinamra , I think what you are asking totally unrelated to this issue. If I am wrong please clarify in details your question. Or open another issue asking this question.

**Comment by fengshenhai-0727** [comment]
@ndresx Any update on this issue? I have been trying to re-render the countdown again once it stops but I got the same issue, where it gets stuck.

**Comment by darol100** [comment]
@fengshenhai-0727 have you tried to restart the component in the last second? Similar to the example I provide at https://github.com/ndresx/react-countdown/issues/8#issuecomment-357052816

**Comment by zhuyifan2013** [comment]
@ndresx   what do you mean `key` attribute in your example https://codesandbox.io/s/ykk86m6o29 ?

**Comment by GruFFix** [comment]
@ndresx When will the fix ?

**Comment by tgfischer** [comment]
@zhuyifan2013 If you change the `key` prop of any component, the component is re-mounted. So if you set the `key` to the date that is being updated, then the `Countdown` will reset as you expect

```
<Countdown
  key={date.toString()}
  date={date.toDate()}
  onComplete={doThing}
/>
```

**Comment by ndresx** [comment]
I know guys, this request is quite old... but I'm still updating it for the sake of completeness.

I really think that the simplest and cleanest solution to this is to update the `key` attribute as we have discussed before because it also avoids any kind of problems with the `date` prop comparison. Updating the docs to contain that piece of information should be enough unless somebody has a better idea?

**Comment by leafyshark** [comment]
> @zhuyifan2013 If you change the `key` prop of any component, the component is re-mounted. So if you set the `key` to the date that is being updated, then the `Countdown` will reset as you expect
> 
> ```
> <Countdown
>   key={date.toString()}
>   date={date.toDate()}
>   onComplete={updateDate}
> />
> ```
> 
> See: https://stackoverflow.com/a/48451229/2455765

Jeez, the amount of time it took to find an answer is beyond belief.

**Comment by alilishan** [comment]
> @zhuyifan2013 If you change the `key` prop of any component, the component is re-mounted. So if you set the `key` to the date that is being updated, then the `Countdown` will reset as you expect
> 
> ```
> <Countdown
>   key={date.toString()}
>   date={date.toDate()}
>   onComplete={updateDate}
> />
> ```
> 
> See: https://stackoverflow.com/a/48451229/2455765

THIS IS IT!! Thank you thank you .. Finally!!!
