### ISSUE TITLE
Countdown freezes on restart via prop change

### ISSUE THREAD

**Issue by zroper** [ndresx/react-countdown#86]
This might be more of a react issue, but maybe someone can help.

I am passing props to the countdown component for date and onComplete. The onComplete prop is a function that makes an API call and gets a new date. The timer successfully counts down to the initial date, the onComplete function is successfully called and the timer resets. However, the timer then freezes and no longer counts down.

```js
<Countdown date={this.props.date} precision={3} onComplete={this.props.onComplete}/>
```
Perhaps there is a better way to restructure the component so that it successfully restarts.

**Comment by ndresx** [comment]
Hi, I agree that the component needs some restructuring when it comes to this! In the meantime, you could try to pass a key to the component to force a re-mount, if that's possible in your scenario?

```ts
<Countdown key={this.props.date} date={this.props.date} precision={3} onComplete={this.props.onComplete}/>
```

**Comment by zroper** [comment]
Thanks for the response. That fixed it! I guess this was more of a react issue.

**Comment by pieeee** [comment]
> Hi, I agree that the component needs some restructuring when it comes to this! In the meantime, you could try to pass a key to the component to force a re-mount, if that's possible in your scenario?
> 
> ```ts
> <Countdown key={this.props.date} date={this.props.date} precision={3} onComplete={this.props.onComplete}/>
> ```

setting a key fixed the problem. Thank you
