### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by moek** [ndresx/react-countdown#90]
Hi,

thanks for your component, it's great to use :)

Yet I have an issue with Typescript that I could not really solve.

I get the following Typescript error:

> Type 'Countdown' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

The complete message:

```
src/Countdown.tsx:27:5 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

27     <Countdown date={date} renderer={renderCountdown} />
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/Countdown.tsx:27:6 - error TS2786: 'Countdown' cannot be used as a JSX component.
  Its instance type 'Countdown' is not a valid JSX element.
    Type 'Countdown' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

27     <Countdown date={date} renderer={renderCountdown} />
        ~~~~~~~~~

[11:33:22 AM] Found 2 errors. Watching for file changes.
```

That's basically my file:

```
import * as React from 'react'
import Countdown, { zeroPad } from 'react-countdown'

const renderCountdown = ({ days, hours, minutes, seconds, completed }) => {
    if (completed) {
        return <div>You are good to go!</div>
    } else {
        return (
            <div>
                <div>{zeroPad(days)}</div>
                <div>:</div>
                <div>{zeroPad(hours)}</div>
                <div>:</div>
                <div>{zeroPad(minutes)}</div>
                <div>:</div>
                <div>{zeroPad(seconds)}</div>
            </div>
        )
    }
}

interface IProps {
    date: string
}

const CountdownWrapper = ({ date }: IProps) => (
    <Countdown date={date} renderer={renderCountdown} />
)

export default CountdownWrapper
```

Does anybody else have the issue or know how to solve it?

NOTE: I got rid of the message by the following hack: `const CountdownWithoutTyping = Countdown as any`

**Comment by moek** [comment]
I am using 3.9.6 of typescript and 16.13.1 of react.

**Comment by ndresx** [comment]
This should be fixed now with version `v2.2.2`. Thanks again for reporting this issue!

**Comment by pr1ntr** [comment]
still happening on TS 4.3 and 4.8

**Comment by ndresx** [comment]
Hi @pr1ntr, I was trying to reproduce this, but couldn't get there. https://codesandbox.io/s/boring-lewin-yg2fms?file=/src/index.tsx

Could you please provide an example?

**Comment by pr1ntr** [comment]
o you know... i may not have updated TS in my package. I'll check back with you on monday.
