### ISSUE TITLE
Infinite renderer

### ISSUE THREAD

**Issue by PolinaBobrovnik** [ndresx/react-countdown#97]
I noticed that if you pass date before Date.now() then renderer is executed infinitely with complete = true. Is it expected behavior?

**Comment by ndresx** [comment]
Hi @PolinaBobrovnik! Thank you for reporting this issue. This is not the expected behavior and should get only executed only once in this case.

**Comment by SK-CSE** [comment]
yes a similar issue is happening if we want to reload the class component itself after the timer finished  
[detail](https://github.com/ndresx/react-countdown/issues/99)

**Comment by ndresx** [comment]
This issue has been fixed now in the latest version. Thanks again for taking the time to report this!
